Name:           perl-Finance-YahooQuote
Version:        0.25
Release:        1%{?dist}
Summary:        Get stock quotes from Yahoo! Finance
License:        CHECK(Distributable)
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Finance-YahooQuote/
Source0:        http://www.cpan.org/authors/id/E/ED/EDD/Finance-YahooQuote-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(HTML::Parser) >= 2.2
BuildRequires:  perl(HTTP::Request) >= 1.23
BuildRequires:  perl(LWP::UserAgent) >= 1.62
BuildRequires:  perl(Text::ParseWords) >= 3.1
Requires:       perl(HTML::Parser) >= 2.2
Requires:       perl(HTTP::Request) >= 1.23
Requires:       perl(LWP::UserAgent) >= 1.62
Requires:       perl(Text::ParseWords) >= 3.1
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module gets stock quotes from Yahoo! Finance. The getonequote function
will return a quote for a single stock symbol, while the getquote function
will return a quote for each of the stock symbols passed to it.
getcustomquote allows to specify a format other than the default to take
advantage of the extended range of available information.

%prep
%setup -q -n Finance-YahooQuote-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc CHANGES CHANGES.old GNU-LICENSE META.json README yahooquote
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Wed May 04 2016 dave.puchyr@avaritia.com 0.25-1
- Specfile autogenerated by cpanspec 1.78.
